[template.environment]
  DXP_URL = "DXP_URL"
  OPTIMIZELY_CONTENTGRAPH_SECRET = "OPTIMIZELY_CONTENTGRAPH_SECRET"
  OPTIMIZELY_CONTENTGRAPH_APP_KEY = "OPTIMIZELY_CONTENTGRAPH_APP_KEY"
  OPTIMIZELY_CONTENTGRAPH_SINGLE_KEY = "OPTIMIZELY_CONTENTGRAPH_SINGLE_KEY"
